# Generated by Django 5.1.3 on 2024-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0003_alter_notification_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type_of_notification",
            field=models.CharField(
                choices=[
                    ("new_friendrequest", "New friendrequest"),
                    ("accepted_friendrequest", "Accepted friendrequest"),
                    ("rejected_friendrequest", "Rejected friendrequest"),
                    ("post_like", "Post like"),
                    ("post_comment", "Post_comment"),
                ],
                max_length=50,
            ),
        ),
    ]
