# Generated by Django 5.1.3 on 2024-11-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_friends_user_friends_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.RemoveField(
            model_name='user',
            name='friends_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='people_you_may_know',
        ),
        migrations.RemoveField(
            model_name='user',
            name='posts_count',
        ),
    ]
