# Generated by Django 5.1.3 on 2024-11-24 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_like_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='liked',
        ),
    ]
