# Generated by Django 5.1.3 on 2024-11-25 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_post_comments_count_comment_post_comments"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ("created_at",)},
        ),
    ]
