# Generated by Django 5.1.3 on 2024-11-29 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0008_trend"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_private",
            field=models.BooleanField(default=False),
        ),
    ]
